//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITV.MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCTIONS
    {
        public FUNCTIONS()
        {
            this.ROLES = new HashSet<ROLES>();
        }
    
        public int FUNC_ID { get; set; }
        public string NODE_ID { get; set; }
        public string PARENT_ID { get; set; }
        public string MENU_TEXT { get; set; }
        public string MENU_VALUE { get; set; }
        public Nullable<int> MENU_LEVEL { get; set; }
        public byte MENU_IS_USE { get; set; }
        public byte MENU_SORT { get; set; }
    
        public virtual ICollection<ROLES> ROLES { get; set; }
    }
}
