//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITV.MDL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ITVContext : DbContext
    {
        public ITVContext()
            : base("name=ITVContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FUNCTIONS> FUNCTIONS { get; set; }
        public virtual DbSet<OPERATORS> OPERATORS { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<NumSeq> NumSeq { get; set; }
    
        public virtual ObjectResult<string> dpPMT_SGetMaintainSeq(string maintainCate)
        {
            var maintainCateParameter = maintainCate != null ?
                new ObjectParameter("MaintainCate", maintainCate) :
                new ObjectParameter("MaintainCate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("dpPMT_SGetMaintainSeq", maintainCateParameter);
        }
    }
}
