//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITV.MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES
    {
        public ROLES()
        {
            this.OPERATORS = new HashSet<OPERATORS>();
            this.FUNCTIONS = new HashSet<FUNCTIONS>();
        }
    
        public int ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public byte ROLE_IS_USE { get; set; }
    
        public virtual ICollection<OPERATORS> OPERATORS { get; set; }
        public virtual ICollection<FUNCTIONS> FUNCTIONS { get; set; }
    }
}
